### PR TITLE
Preserve SVG content

### PR DESCRIPTION
**Pull request by maxkoryukov**
There was an issue with SVG-inlining. Lets consider on example.

`my.svg`:

```svg
<!-- valid comment on the top of the file
with LICENSE or COPYRIGHTS
-->

<svg>...</svg>
```

If you apply `gulp-inline` to `my.svg`, you will lost comment on the top of the file.

This PR solves this problem, preserving the comment

### CODE REVIEW

**Comment by maxkoryukov** [comment]
ping @ashaffer

**Comment by ashaffer** [comment]
Hey, thanks for this and sorry for not responding earlier. Can you make it so that the tests pass?

**Comment by maxkoryukov** [comment]
There was a trailing **newline** at the end of the `basic.svg`, I removed it

**Comment by ashaffer** [comment]
Great thanks

**Pull request merged**
